# Generated by Django 4.2.5 on 2023-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_MUSIC", "0002_alter_espinfoentity_tempo_de_estudo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="espinfoentity",
            name="tempo_de_estudo",
            field=models.FloatField(default=0.0),
        ),
    ]
